### ISSUE TITLE
js-plugin-sass use additionalData and `@use` load file failed

### ISSUE THREAD

**Issue by shulandmimi** [farm-fe/farm#1091]
### Steps to reproduce

main latest

1. `cd examples/sass`

2. create file

src/styles/scss/global.scss
```scss
@import "./scrollbar.scss";
```

src/styles/scss/scrollbar.scss
```scss
@mixin scrollbar($size: 8px, $color: #d9d9d9) {
	scrollbar-width: thin;
	scrollbar-color: $color transparent;

	&::-webkit-scrollbar-thumb {
		background-color: $color;
		border-radius: $size;
	}
	&::-webkit-scrollbar-thumb:hover {
		background-color: $color;
		border-radius: $size;
	}
	&::-webkit-scrollbar {
		width: $size;
		height: $size;
	}
	&::-webkit-scrollbar-track-piece {
		background-color: rgba(0, 0, 0, 0);
		border-radius: 0;
	}
}
```

3. farm.config.ts

```ts
export default {
	plugins: [
		// ..
		farmSassPlugin({
	      additionalData: `@use "@/styles/scss/global.scss" as *;`
	    })
	]
}
```

4. pnpm run build

### What is expected?

build success

### What is actually happening?

```
[ Farm ] Error: Transform `src/style/index.scss` failed.
Error: [@farmfe/js-plugin-sass transform Error] can not resolve PluginResolveHookParam { source: "file:/farm/farm-local/examples/sass/@/styles/scss/scrollbar.scss", importer: Some(ModuleId { relative_path: "src/style/index.scss", query_string: "" }), kind: CssAtImport }
  ╷
1 │ @import "./scrollbar.scss";
  │         ^^^^^^^^^^^^^^^^^^
  ╵
  @/styles/scss/global.scss 1:9  @use
  src/style/index.scss 1:1       root stylesheet
```

### System Info

```Shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 7.18 GB / 31.22 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - /run/user/1000/fnm_multishells/231637_1711686122058/bin/node
    Yarn: 1.22.22 - ~/.local/share/pnpm/global/yarn
    npm: 10.1.0 - /run/user/1000/fnm_multishells/231637_1711686122058/bin/npm
    pnpm: 8.13.1 - /run/user/1000/fnm_multishells/231637_1711686122058/bin/pnpm
  npmPackages:
    @farmfe/core: workspace:* => 1.0.8
```
