### ISSUE TITLE
Url() in Css does not recognize as dependencies

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#361]
### Steps to reproduce

write a css with `url()`:

```css
.indro-right {
        background: url('./img/part1-bg.png') no-repeat;
        background-size: contain;
        position: absolute;
        right: 0;
        top: -20px;
        width: 500px;
        height: 400px;
      }
```

### What is expected?

The image in url() should be compiled and replaced.

### What is actually happening?

The link in url is unchanged

### System Info

```Shell
macos
```
