### ISSUE TITLE
`@import 'animate.css'` does not work in dev mode

### ISSUE THREAD

**Issue by wre232114** [farm-fe/farm#425]
### Steps to reproduce

create a scss file like:
```scss
@import "./variables.scss";
@import "animate.css";

body {
  font-size: $rootFontSize !important;
  color: $rootFontColor !important;
  line-height: 25px !important;
}
```

then import this scss file and run npm start, `animate.css` is compiled but never executed, so animate.css does not work.

### What is expected?

execute @import 'animate.css' in dev mode.

### What is actually happening?

not work

### System Info

```Shell
windows @farmfe/core@0.9.5
```
